title: Next Apps Lab

description: Building the next generation of mobile experiences.

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

logo: "/assets/images/logo.png"

minimal_mistakes_skin: "default"